before_script:
  - mix local.hex --force
  - mix local.rebar --force

build_coordinator:
  stage: build
  tags:
    - stressgrid
  variables:
    MIX_ENV: prod
  script:
    - pushd coordinator/management/
    - npm install
    - npm run build-css
    - npm run build
    - popd
    - pushd coordinator/
    - mix deps.get
    - mix release
    - popd

build_generator:
  stage: build
  tags:
    - stressgrid
  variables:
    MIX_ENV: prod
  script:
    - pushd generator/
    - mix deps.get
    - mix release
    - popd

build_client:
  stage: build
  tags:
    - stressgrid
  script:
    - pushd client/
    - npm install
    - npm run build
    - popd

