version: '3.8'

services:
  coordinator:
    build: .
    command: ["/app/coordinator/_build/prod/rel/coordinator/bin/coordinator", "start"]
    environment:
      - PHX_SERVER=true
      - SECRET_KEY_BASE=3sUQ4Ig0XDzXiqGlDf9kBl1MVP4AaHgtzh7l35imGb0BbKt7QkrpMQMuwWRLqcjv
      - LOGGER_LEVEL=error
    ports:
      - "4000:4000"
      - "9696:9696"

  generator-1:
    build: .
    command: ["/app/generator/_build/prod/rel/generator/bin/generator", "start"]
    environment:
      - COORDINATOR_URL=ws://coordinator:9696
      - GENERATOR_ID=generator-1
      - LOGGER_LEVEL=error
    depends_on:
      - coordinator
