name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GiHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
       
    - name: Get current date
      id: get-current-date
      run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Get repo owner
      id: get-repo-owner
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and Publish the Docker image
      env:
        TAG_NAME: ghcr.io/${{ env.REPO_OWNER }}/stressgrid:${{ env.CURRENT_DATE }}
      run: |
        docker build . --file Dockerfile --tag $TAG_NAME
        docker push $TAG_NAME
